project:
  type: website
  output-dir: docs

website:
  title: "Rare Nostriches"
  favicon: images/nostr_land.jpeg
  navbar:
    right:
      - text: "About"
        href: about.qmd

format:
  html:
    theme: pulse
    css: styles.css
    toc: true



